############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 2013 Xilinx Inc. All rights reserved.
############################################################
open_project hipacc_project
set_top hipaccRun
add_files hipacc_run.cc
add_files -tb main_vivado.cc
open_solution "solution1"
set_part {xc7z100ffg900-2}
create_clock -period 3.0 -name default
source "./directives.tcl"
csim_design -ldflags {-lrt} -clean -compiler clang
config_bind -effort high
config_schedule -effort high
#config_compile -unsafe_math_optimizations
csynth_design
#cosim_design -ldflags {-lrt} -trace_level none
#export_design -format ip_catalog -description "An IP generated by Vivado HLS" -vendor "xilinx.com" -library "hls" -version "1.0"
export_design -format ip_catalog -evaluate vhdl
exit
